### ISSUE TITLE
False Positive Salsify/StyleDig

### ISSUE THREAD

**Issue by will89** [salsify/salsify_rubocop#20]
The following example feels like an odd scenario to raise this rubocop warning.
```
hash[key1] ||= {}
hash[key1][key2] ||= {}
hash[key1][key2][key3] = 'Some value' # raises Salsify/StyleDig
```

**Comment by tjwp** [comment]
We fixed this false positive and some others here: https://github.com/ezcater/ezcater_rubocop/blob/master/lib/rubocop/cop/ezcater/style_dig.rb
